name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
    env:
      SLN_FILE_NATIVE: MochiSharp.sln
      SLN_FILE_MANAGED: MochiSharp-Managed.sln
      PREMAKE_VERSION: 5.0.0-beta7

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Setup MSBuild (Visual Studio 2022)
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[17.0,18.0)'

      - name: Install Premake
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $version = "${{ env.PREMAKE_VERSION }}"
          $zipUrl = "https://github.com/premake/premake-core/releases/download/v$version/premake-$version-windows.zip"
          $dst = "$PWD/tools"
          New-Item -ItemType Directory -Force -Path $dst | Out-Null
          $zipPath = "$dst/premake.zip"
          Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $dst -Force
          "$dst" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Generate Solution with Premake5
        shell: pwsh
        run: |
          premake5 vs2022 --file=premake5-native.lua ^
          premake5 vs2022 --file=premake5-managed.lua

      - name: Restore NuGet packages
        shell: pwsh
        run: msbuild $env:SLN_FILE_MANAGED /t:Restore /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU"

      - name: Build native solution
        shell: pwsh
        run: |
          msbuild $env:SLN_FILE_MANAGED /t:Build /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU" /m ^
          msbuild $env:SLN_FILE_NATIVE /t:Build /p:Configuration=${{ matrix.configuration }} /p:Platform="x64" /m
